import { ThemeConfig } from '../store/theme';

export const DEPARTMENT_THEMES: Record<string, Partial<ThemeConfig>> = {
  'administration': {
    primary: '#002147',
    accent: '#D4AF37',
    bgBase: '#FFFFFF',
    headingFont: 'Playfair Display',
    bodyFont: 'Inter',
  },
  'sales': {
    primary: '#065F46',
    accent: '#D1FAE5',
    bgBase: '#FFFFFF',
    headingFont: 'Montserrat',
    bodyFont: 'Inter',
  },
  'marketing': {
    primary: '#EA580C',
    accent: '#36454F',
    bgBase: '#FDF5E6',
    headingFont: 'Poppins',
    bodyFont: 'Inter',
  },
  'customer-service': {
    primary: '#FF7F50',
    accent: '#FFFDD0',
    bgBase: '#F5F5F5',
    headingFont: 'Lato',
    bodyFont: 'Inter',
  },
  'production': {
    primary: '#4682B4',
    accent: '#C0C0C0',
    bgBase: '#FFFFFF',
    headingFont: 'Roboto',
    bodyFont: 'Inter',
  },
  'operations': {
    primary: '#008080',
    accent: '#D3D3D3',
    bgBase: '#FFFFFF',
    headingFont: 'IBM Plex Sans',
    bodyFont: 'Inter',
  },
  'transport': {
    primary: '#FFBF00',
    accent: '#5C4033',
    bgBase: '#FFFDD0',
    headingFont: 'Nunito',
    bodyFont: 'Inter',
  },
  'hr': {
    primary: '#800080',
    accent: '#FFB6C1',
    bgBase: '#FFFFFF',
    headingFont: 'Quicksand',
    bodyFont: 'Inter',
  },
  'it': {
    primary: '#00FF00',
    accent: '#000000',
    bgBase: '#1A1A1A',
    headingFont: 'JetBrains Mono',
    bodyFont: 'Source Code Pro',
  },
  'finance': {
    primary: '#228B22',
    accent: '#D4AF37',
    bgBase: '#FAF9F6',
    headingFont: 'Merriweather',
    bodyFont: 'Inter',
  },
  'business-development': {
    primary: '#4169E1',
    accent: '#FFFF00',
    bgBase: '#FFFFFF',
    headingFont: 'Space Grotesk',
    bodyFont: 'Inter',
  },
  'communications': {
    primary: '#DC143C',
    accent: '#FFFFF0',
    bgBase: '#FFFFFF',
    headingFont: 'Libre Baskerville',
    bodyFont: 'Inter',
  },
  'security': {
    primary: '#556B2F',
    accent: '#2F4F4F',
    bgBase: '#FFFFFF',
    headingFont: 'Oswald',
    bodyFont: 'Roboto Mono',
  },
  'housekeeping': {
    primary: '#87CEEB',
    accent: '#FFFFFF',
    bgBase: '#F0F8FF',
    headingFont: 'Nunito Sans',
    bodyFont: 'Inter',
  },
  'quality-control': {
    primary: '#4B0082',
    accent: '#FFBF00',
    bgBase: '#FFFFFF',
    headingFont: 'DM Sans',
    bodyFont: 'Inter',
  },
  'warehouse': {
    primary: '#708090',
    accent: '#008080',
    bgBase: '#D3D3D3',
    headingFont: 'Manrope',
    bodyFont: 'Inter',
  },
  'maintenance': {
    primary: '#000080',
    accent: '#FFBF00',
    bgBase: '#FFFFFF',
    headingFont: 'Work Sans',
    bodyFont: 'Inter',
  },
  'procurement': {
    primary: '#000080',
    accent: '#FFBF00',
    bgBase: '#FFFFFF',
    headingFont: 'IBM Plex Sans',
    bodyFont: 'Inter',
  },
  'projects': {
    primary: '#008080',
    accent: '#FFFFFF',
    bgBase: '#FFFFFF',
    headingFont: 'Inter',
    bodyFont: 'Inter',
  },
  'loyalty': {
    primary: '#FF00FF',
    accent: '#FFD700',
    bgBase: '#FFFFFF',
    headingFont: 'Comfortaa',
    bodyFont: 'Inter',
  },
  'claims': {
    primary: '#FF0000',
    accent: '#808080',
    bgBase: '#FFC0CB',
    headingFont: 'Work Sans',
    bodyFont: 'Inter',
  },
  'feedback': {
    primary: '#FF007F',
    accent: '#FFBF00',
    bgBase: '#FFFFFF',
    headingFont: 'Plus Jakarta Sans',
    bodyFont: 'Inter',
  },
  'hse': {
    primary: '#008000',
    accent: '#FFFF00',
    bgBase: '#FFFFFF',
    headingFont: 'Karla',
    bodyFont: 'Inter',
  },
};
